apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-api
  namespace: web
spec:
  selector:
    matchLabels:
      app: tripviewer-api
  template:
    metadata:
      labels:
        app: tripviewer-api # the label for the pods and the deployments
    spec:
      containers:
      - name: tripviewer-api
        image: registryudo2566.azurecr.io/tripinsights/tripviewer:latest # IMPORTANT: update with your own repository
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # the application listens to this port
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: http://userprofile-api.api.svc.cluster.local:80
        - name: TRIPS_API_ENDPOINT
          value: http://trips-api.api.svc.cluster.local:80
        resources:
          requests: # minimum resources required
            cpu: 250m
            memory: 64Mi
          limits: # maximum resources allocated
            cpu: 1000m #1000m is one full core
            memory: 256Mi
        # readinessProbe: # is the container ready to receive traffic?
        #   httpGet:
        #     port: 80
        #     path: /api/tripviewer/healthcheck
        # livenessProbe: # is the container healthy?
        #   httpGet:
        #     port: 80
        #     path: /api/tripviewer/healthcheck