apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-api
  namespace: api
spec:
  selector:
    matchLabels:
      app: userprofile-api
  template:
    metadata:
      labels:
        app: userprofile-api # the label for the pods and the deployments
    spec:
      containers:
      - name: userprofile-api
        image: registryudo2566.azurecr.io/tripinsights/userprofile:1.0 # IMPORTANT: update with your own repository
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # the application listens to this port
        env:
        - name: SQL_USER # the application expects to find connection details in this environment variable
          valueFrom:
            secretKeyRef:
              name: sqlsecret # the name of the Kubernetes secret containing the data
              key: SQL_USER # the key inside the Kubernetes secret containing the data
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlsecret # the name of the Kubernetes secret containing the data
              key: SQL_PASSWORD # the key inside the Kubernetes secret containing the data
        - name: SQL_SERVER
          value: sqlserverudo2566.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB
        resources:
          requests: # minimum resources required
            cpu: 500m
            memory: 64Mi
          limits: # maximum resources allocated
            cpu: 1000m #1000m is one full core
            memory: 256Mi
        # readinessProbe: # is the container ready to receive traffic?
        #   httpGet:
        #     port: 80
        #     path: /api/user/healthcheck
        # livenessProbe: # is the container healthy?
        #   httpGet:
        #     port: 80
        #     path: /api/user/healthcheck