apiVersion: v1
kind: Service
metadata:
  name: userprofile-api
  namespace: api
spec:
  selector:
    app: userprofile-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP