apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api
  name: api-fullaccess-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: web
  name: web-fullaccess-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api
  name: api-reader-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: web
  name: web-reader-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get","list","watch"]