# This is a SecretProviderClass example using user-assigned identity to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "b4b0502c-c1b1-4b5c-8d67-136e07ed5dce"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "kv-tripinsights"        # Set to the name of your Azure Key Vault instance
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQL-USER
          objectType: secret              # object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
          objectAlias: "SQL_USER"
        - |
          objectName: SQL-PASSWORD
          objectType: secret
          objectVersion: ""
          objectAlias: "SQL_PASSWORD"
    tenantId: "8aa56ed7-40b9-4bf4-933d-67d5fc35b41b"                 # The tenant ID of the Azure Key Vault instance
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-sync
spec:
  provider: azure                             
