apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-api
  namespace: api
spec:
  selector:
    matchLabels:
      app: user-java-api
  template:
    metadata:
      labels:
        app: user-java-api # the label for the pods and the deployments
    spec:
      containers:
      - name: user-java-api
        image: registryudo2566.azurecr.io/tripinsights/user-java:1.0 # IMPORTANT: update with your own repository
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # the application listens to this port
        env:
        - name: SQL_SERVER
          value: sqlserverudo2566.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB
        resources:
          requests: # minimum resources required
            cpu: 250m
            memory: 64Mi
          limits: # maximum resources allocated
            cpu: 1000m #1000m is one full core
            memory: 256Mi
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets"
          readOnly: true        
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
        # readinessProbe: # is the container ready to receive traffic?
        #   httpGet:
        #     port: 80
        #     path: /api/user-java/healthcheck
        # livenessProbe: # is the container healthy?
        #   httpGet:
        #     port: 80
        #     path: /api/user-java/healthcheck