apiVersion: v1
kind: Service
metadata:
  name: user-java-api
  namespace: api
spec:
  selector:
    app: user-java-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP