apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-api
spec:
  selector:
    matchLabels:
      app: poi-api
  template:
    metadata:
      labels:
        app: poi-api # the label for the pods and the deployments
    spec:
      containers:
      - name: poi-api
        image: registryudo2566.azurecr.io/tripinsights/poi:1.0 # IMPORTANT: update with your own repository
        imagePullPolicy: Always
        ports:
        - containerPort: 3000 # the application listens to this port
        env:
        - name: SQL_USER # the application expects to find connection details in this environment variable
          value: sqladminuDo2566
          # valueFrom:
          #   secretKeyRef:
          #     name: sqlserversecret # the name of the Kubernetes secret containing the data
          #     key: MONGOCONNECTION # the key inside the Kubernetes secret containing the data
        - name: SQL_PASSWORD
          value: tC0kx0Sd4
        - name: SQL_SERVER
          value: sqlserverudo2566.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB
        resources:
          requests: # minimum resources required
            cpu: 500m
            memory: 64Mi
          limits: # maximum resources allocated
            cpu: 1000m #1000m is one full core
            memory: 256Mi
        # readinessProbe: # is the container ready to receive traffic?
        #   httpGet:
        #     port: 3000
        #     path: /api/poi/healthcheck
        # livenessProbe: # is the container healthy?
        #   httpGet:
        #     port: 3000
        #     path: /api/poi/healthcheck